name: sugarbetes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.14
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_svg: ^1.0.3
  syncfusion_flutter_charts: ^20.1.52
  http: ^0.13.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/logo.jpg
    - assets/images/BloodSugar.jpg
    - assets/images/sugar.jpg
    - assets/images/user-profile.jpg
    - assets/images/insulin_treatment.jpg
    - assets/images/insulin_reminder.jpg
    - assets/images/IMG_8830.jpg
    - assets/svg/time_management.svg
    - assets/svg/database.svg
    - assets/svg/food.svg
    - assets/images/notfound.png

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

    - family: ArchitectsDaughter
      fonts:
        - asset: assets/fonts/ArchitectsDaughter-Regular.ttf

    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf

    - family: LobsterTwo-Regular
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
